doctrine:
    dbal:
        types:
            # LET special type to utc DateTime
            datetime: App\DBAL\Types\UTCDateTimeType
    orm:
        dql:
            numeric_functions:
api_platform:
    swagger:
         api_keys:
             apiKey:
                name: Authorization
                type: header
                
services:
    App\Swagger\SwaggerDecorator:
        decorates: 'api_platform.swagger.normalizer.documentation'
        arguments: ['@App\Swagger\SwaggerDecorator.inner']
        autoconfigure: false