#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# api/config/routes.yaml
api_login_check:
    path: /api/login_check
    options:
        expose: true
app_logout:
    path: /logout
    options:
        expose: true